ci: add -Werror
tcc doesn't have a way to disable certain warnings, it seems. so just
add a dummy `return 0` to workaround glibc's no-op `__attribute__`
macro.

additionally add:

-Wno-error=cpp to workaround libbsd triggering `#warning` on musl.
-Wno-error=pedantic because autohell is broken.
	conftest.c:19: error: ISO C forbids an empty translation unit [-Werror=pedantic]

Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/283